import AN from './maps/andamannicobarislands.json'
import AP from './maps/andhrapradesh.json'
import AR from './maps/arunachalpradesh.json'
import AS from './maps/assam.json'
import BR from './maps/bihar.json'
import CH from './maps/chandigarh.json'
import CT from './maps/chhattisgarh.json'
import DL from './maps/delhi.json'
import DD from './maps/dnh-and-dd.json'
import GA from './maps/goa.json'
import GJ from './maps/gujarat.json'
import HR from './maps/haryana.json'
import HP from './maps/himachalpradesh.json'
import JK from './maps/jammukashmir.json'
import JH from './maps/jharkhand.json'
import KA from './maps/karnataka.json'
import KL from './maps/kerala.json'
import LA from './maps/ladakh.json'
import LD from './maps/lakshadweep.json'
import MP from './maps/madhyapradesh.json'
import MH from './maps/maharashtra.json'
import MN from './maps/manipur.json'
import ML from './maps/meghalaya.json'
import MZ from './maps/mizoram.json'
import NL from './maps/nagaland.json'
import OR from './maps/odisha.json'
import PY from './maps/puducherry.json'
import PB from './maps/punjab.json'
import RJ from './maps/rajasthan.json'
import SK from './maps/sikkim.json'
import TN from './maps/tamilnadu.json'
import TG from './maps/telangana.json'
import TR from './maps/tripura.json'
import UT from './maps/uttarakhand.json'
import UP from './maps/uttarpradesh.json'
import WB from './maps/westbengal.json'
import DN from './maps/dnh-and-dd.json'


export { BR, AN, AR, AP, AS, CH, CT, DL, DD, GA, GJ, HR, HP, JK, JH, KA, KL, MP, MH, MN, ML, MZ, NL, OR, PB, RJ, SK, TN, TG, TR, UT, UP, WB, PY, LA, LD, DN }

